# Generated by Django 4.1.6 on 2023-02-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsection',
            name='context',
        ),
        migrations.AddField(
            model_name='mainsection',
            name='context1',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainsection',
            name='context2',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainsection',
            name='context3',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
